// <auto-generated />
using System;
using GasBrasilDashboardBiblioteca.Data_Access_Layer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GasBrasilDashboardBiblioteca.Migrations
{
    [DbContext(typeof(TB_CADASTRO_BRUTO_CONTEXT))]
    partial class TBCADASTROBRUTOCONTEXTModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GasBrasilDashboardBiblioteca.Models.TB_CADASTRO_BRUTO", b =>
                {
                    b.Property<int>("ID_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CLIENTE"));

                    b.Property<string>("CLASSE_CONSUMO")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("CLASSE_CONSUMO");

                    b.Property<string>("MUNICIPIO")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("MUNICIPIO");

                    b.HasKey("ID_CLIENTE");

                    b.HasIndex(new[] { "ID_CLIENTE" }, "ID_CLIENTE")
                        .IsUnique();

                    b.ToTable("TB_CADASTRO_BRUTO", (string)null);
                });

            modelBuilder.Entity("GasBrasilDashboardBiblioteca.Models.TB_FATURAMENTO", b =>
                {
                    b.Property<int>("ID_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CLIENTE"));

                    b.Property<string>("CONSUMO_M3")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CONSUMO_M3");

                    b.Property<DateTime?>("DATA_ARQUIVO")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("DATETIME")
                        .HasColumnName("DATA_ARQUIVO");

                    b.Property<DateTime?>("DATA_REFERENCIA")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("DATETIME")
                        .HasColumnName("DATA_REFERENCIA");

                    b.HasKey("ID_CLIENTE");

                    b.HasIndex(new[] { "ID_CLIENTE" }, "ID_CLIENTE")
                        .IsUnique();

                    b.ToTable("TB_FATURAMENTO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
